language: python
python:
- 2.7
install:
- pip install .
script: py.test
notifications:
  irc:
    channels:
    - irc.freenode.org#majerteam-travis
    on_success: change
deploy:
  provider: pypi
  user: tonthon21
  password:
    secure: C3b/lS6d2b1zfOyl0NTXjkX37Gq3uzyLck9EBVVBnJbsEy8Ic3DWAcYsq/sfh14uatFmUppImcxYr9tRyzFHiowYcdeFV3RIANR98cCrwGn8kVJdxBqS6HZjpIOU5WSBHfb84GtSgcnjS9nyjk+ZrBkAqUgKZpqL/OINhI7g4w8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: majerteam/deform_extensions
